
#General mod settings
[general]
	#Uses list of people to have senses spawned for
	whiteListUsedSenses = false
	#List of people to have omniscient targetting effect
	whitelistOmniscientTargettedPlayers = "jay4u, 1488_pepe, cutiepowpow"
	#List of people to have senses spawned for
	whitelistSenses = "jay4u, 1488_pepe, cutiepowpow"
	#List of people to have spawning of zombies for
	whitelistExtraSpawning = "jay4u, 1488_pepe, cutiepowpow"
	#Uses list of people to have omniscient targetting effect
	whiteListUsedOmniscient = true
	#Uses list of people to have spawning of zombies for
	whiteListUsedExtraSpawning = false

