
#Flashlight Config
[flashlight]
	#You can set this to a higher value, but it would cause more lag.
	#Range: > 0
	max_radius = 5
	#You can set this to a higher value, but it would cause more lag.
	#Range: > 0
	max_distance = 8
	#You can set this to a lower value, or even zero, but it would cause PLENTY more FPS reduce.
	#Range: 0 ~ 1000
	sleep_time = 200

